### PR TITLE
Server Send ratings

### PR DESCRIPTION
**Pull request by Shosoul**
Send the ratings of players in a third table so that we can ascertain the true ratings of players instead of guessing based off the leaderboard.

### CODE REVIEW

**Review by JamesVanBoxtel — COMMENTED** [review]
Great start! Might as well write the client code too to make sure its working right. We might want to send the temporary rating of players still doing placement matches as well. 

And obviously we don't want to commit the log change and shosoul connection changes

**Comment by Shosoul** [comment]
> Great start! Might as well write the client code too to make sure its working right. We might want to send the temporary rating of players still doing placement matches as well.
> 
> And obviously we don't want to commit the log change and shosoul connection changes

Do you mean temporary ratings as in placement ratings? Also, I'm thinking of doing the client code change in a separate pull since this probably won't be live right away.

And yea, those temporary changes will go away when I finish this.

**Comment by Shosoul** [comment]
Any update for here?

**Comment by JamesVanBoxtel** [comment]
I haven't got to test this yet, and yeah I mean the placement match ratings

**Comment by Shosoul** [comment]
Changes were moved to #410

**Pull request closed without merging**
