### PR TITLE
Attempt to fix some network issues

### PR DESCRIPTION
**Pull request by LittleEndu**

### CODE REVIEW

**Comment by jon12156** [comment]
@LittleEndu you'd mentioned this didn't work.  Should I close this PR?

**Comment by LittleEndu** [comment]
The commit I reverted didn't work. I'm not really sure about the other ones, I don't really know what triggers the vs local not working after multi bug.

**Comment by jon12156** [comment]
This seems buggy.  If I spectate a match (or play 2p online), then leave and go to 1p vs yourself, where it used to not let the cursor move in the 1p vs yourself char select, and then bluescreen when you hit Esc, now it doesn't let me move in 1p vs yourself, and when I hit Esc, it goes to an empty 2p online lobby, stuck "logging in..."

**Comment by jon12156** [comment]
I think there's a better way for me to do this, but Idk.  I've added a commit to this PR, but on a different branch.  Anyway, 2p spectating to 1p vs yourself works now.  I'll close this PR now. and push my branch to master.

**Comment by LittleEndu** [comment]
Next time you could just push to my PR.

**Pull request closed without merging**
