### PR TITLE
Improved Endless, Puzzles, and Time Attack

### PR DESCRIPTION
**Pull request by JamesVanBoxtel**
This change provides various quality of life improvements to the UI and easy to fix features for puzzle mode and endless  Puzzles can now have random colors if turned on in the menu
The Stack class now has named parameters as it was getting to hard to manage
You can now set the level for endless and time attack, replays and scores will not be saved for now
You can now set the level of puzzles in the menu
On screen up / down touch / mouse controls have been repositioned to be usable on mobile
Left / right on screen controls are now shown when these options do things in the menu
Music and character don’t reset when you retry / go to the next puzzle
Fixed a bug with restarting the puzzle set not starting at the beginning
Stage / character selected are respected in puzzles
Moved Go in timeless / endless to the beginning to make it easier to start

### CODE REVIEW

**Review by Endaris — COMMENTED** [review]
I kind of don't like as much how some menu points for the TA/Endless selection are unresponsive if you have level selected. Not sure if it would be possible but maybe you could make the first menu point a selection between "classic" and "levels" and the rest of the menu changes on the fly based on that selection?
If not then it would be nice if "Speed" could be greyed out or something to make it clear that it is not editable while a level is set.

Also considering whether it might be worth to extract this into its own "simple_select_screen.lua" or similar where you pass in a callback that gives you the extra configs to be selected (e.g. for puzzle) so that it's more universal and you can get rid of the local functions inside the local functions and instead turn them into class functions

**Comment by JamesVanBoxtel** [comment]
Okay I think I resolved all the comments except refactoring to simple_select_screen.lua

I want to hold off on this because alpha hasn't landed and I also know Sankyr is working on a whole menu cleanup

**Review by Shosoul — CHANGES_REQUESTED** [review]
Finally found time to review this!

Not entirely sure the levels are working on puzzle mode, the speed at which the panels pop (specifically `level_to_pop` did not seem to change, I'll see if I can try and find the reason later)

Maybe an option to turn off the arrow buttons in settings (unless the screen can't fit all the options) but it's not a necessary thing to add, just would be kinda cool.

**Comment by Endaris** [comment]
When changing to modern style, the last record / high score options disappear for me, there needs to be an extension in the scores.json to support this change.

**Comment by JamesVanBoxtel** [comment]
> When changing to modern style, the last record / high score options disappear for me, there needs to be an extension in the scores.json to support this change.
> 
> Personally I also don't quite agree with the change in the order of elements, for me the "Go!" still belongs to the second last position before "Back".

The reason I moved it to this way is so its faster to just start if you have a standard difficulty you play on. I also noticed when you finish a game it goes back to the first, so its annoying to keep retrying.

**Comment by JamesVanBoxtel** [comment]
I also didn't record scores for now because we may want to change how the scoring system works for "modern" later.

**Comment by JamesVanBoxtel** [comment]
> level_to_pop

Great catch! I found the problem and fixed it.

**Comment by Endaris** [comment]
> > Personally I also don't quite agree with the change in the order of elements, for me the "Go!" still belongs to the second last position before "Back".
> 
> The reason I moved it to this way is so its faster to just start if you have a standard difficulty you play on. I also noticed when you finish a game it goes back to the first, so its annoying to keep retrying.

I think rather than moving the options, I'd prefer if the "Start" key moved you immediately to the "Go" option and then started on the next input, similar to how escape puts you on "Back".
Personally I really prefer confirming my options and it also seems odd to me functionally if Go and Back are split apart.

**Comment by Endaris** [comment]
I really like the compromise you found with going to go after the initial confirmation, think that's perfect.
One thing that's not 100% smooth imo is that PA memorizes your choice globally, meaning if I played time attack earlier and enter endless, apart from using the exact same settings that were used for time attack earlier, the cursor is already placed on go. I think it would be good if you reset the index to 1 upon exiting the game settings menu to make sure that you can reselect from scratch upon reentering either of those modes anew.

**Comment by JamesVanBoxtel** [comment]
> I really like the compromise you found with going to go after the initial confirmation, think that's perfect.
> One thing that's not 100% smooth imo is that PA memorizes your choice globally, meaning if I played time attack earlier and enter endless, apart from using the exact same settings that were used for time attack earlier, the cursor is already placed on go. I think it would be good if you reset the index to 1 upon exiting the game settings menu to make sure that you can reselect from scratch upon reentering either of those modes anew.

Hmm that was way easier to fix then I expected. Done

**Review by Shosoul — APPROVED** [review]
gg

**Pull request merged**
