### PR TITLE
Fix blurry graphics

### PR DESCRIPTION
**Pull request by JamesVanBoxtel**
We were creating canvases with non standard scales like "0.8654" when you were at odd zoom levels.
This creates all kinds of bad artifacts.
We were also creating fonts with bad scales.
Instead we want to snap DPI to reasonable boundaries. 1, 1.5, 2 etc

This makes almost all graphics look good, but we take special care with the legacy panels to upscale them equally using nearest neighbor so the pixels are consistent no matter where they are on canvas.
Screen Shot 2022-08-07 at 8 43 35 PM
Screen Shot 2022-08-07 at 8 43 19 PM

### CODE REVIEW

**Review by Shosoul — CHANGES_REQUESTED** [review]
Seems to make the panels blurrier. First image is current beta, second one is this change. Becomes easier to tell if you download them both and swap between them
screenshot_v046-2022-08-08-17-12-25beta

screenshot_v046-2022-08-08-17-11-49_notbeta

**Comment by Shosoul** [comment]
oh, and 1.5 scale graphics settings.

**Comment by JamesVanBoxtel** [comment]
So I can go back to it being sharper, but keep in mind it won't be as symmetrical or even in that case, here is a blown up version of what 1.5 scale looks like fully nearest neighbor, vs nearest and then linear.

You can see that its "blurrier" but evenly balanced and all pixels are "square"

Full Nearest Neighbor
Screen Shot 2022-08-08 at 10 06 05 PM

Nearest Neighbor then Linear
Screen Shot 2022-08-08 at 10 06 49 PM

**Comment by Shosoul** [comment]
IMO I would prefer fullest nearest neighbor in this case

**Comment by JamesVanBoxtel** [comment]
Okay I fixed it to use full nearest neighbor, and also aligned the stack canvas so its pixel aligned. 

HD Panels
Screen Shot 2022-08-10 at 7 13 52 PM

Super HD Panels
Screen Shot 2022-08-10 at 7 13 28 PM

Original Panels 
Screen Shot 2022-08-10 at 7 12 53 PM

**Comment by JamesVanBoxtel** [comment]
A couple requirements:

1. The global canvas needs to have scale * canvas size pixels otherwise it will not be able to hold all the details for assets of equal or higher resolution.
2. The high res assets need to scale down linearly for 1.5 scale so they don't look jaggy
3. 1x assets need to be upscaled using "nearest" if they are intended to be blocky. (most TA graphics)
4. 1x assets need to be upscaled using "linear" if they are not intended to be block. ("HD" Panels like Miz's)

The problem is there is no way to know if we are in case 3 or 4 for the most part, so maybe what we should do is assume 3 by default for 1x images. However panels that are 48 tall, we will default to 4.

Then in a future PR we can make a way to override the default for particular images.

**Comment by JamesVanBoxtel** [comment]
Screen Shot 2022-08-11 at 6 05 06 PM

Screen Shot 2022-08-11 at 6 04 53 PM

**Review by Shosoul — APPROVED** [review]

**Pull request merged**
