### PR TITLE
Spectate hotfix

### LINKED ISSUE #644: Crossclient spectating may lead to crashes
In the rework of select_screen I kind of transformed the role of the `character_is_random` value. In the old one it is being used as a boolean in some places and as an id-string in others.
Beta always uses it for the id of the character the player actually selected (opposed to what they will have picked client side).
This seems to cause stable (spectators) of beta players to think that it always wants to randomize on the substage/character level, causing the game to crash as these tables are empty.
grafik

```Lua
if resolve_character_random(cursor_data[1].state) then -- state.character actually gets emptied here
  character_loader_load(cursor_data[1].state.character)
end
cursor_data[1].state.character_display_name = characters[cursor_data[1].state.character].display_name -- trying to index with nil
```

Since this is a compatibility issue, I think it is a lot faster to hotfix this in master rather than trying to bend beta to fit to master's warped interpretation of that attribute.

### PR DESCRIPTION
**Pull request by Endaris**
Think this should fix #644, not entirely sure yet because there was none to spectate so far (and I've been too lazy to fix Windows detecting PA as a trojan the moment I start to play online with myself).
Essentially make the game check if the character/stage is a bundle before you pick a random entry from the subtable.

### CODE REVIEW

**Comment by JamesVanBoxtel** [comment]
Do you know exactly what is changed going over the wire in beta then before?

Unless something being sent over the wire was wrong, we should probably keep the protocol the same.

**Comment by Endaris** [comment]
Good that you asked.
In stable, `character_is_random` could have 3 different values (ignoring the nil cases because that never goes to the server):
`random_character_special_value` if the player actually selected a random character - this would cause the client on the other end to roll the character again, not caring about what it rolled for the players that selected it.
the `character_id` of a bundle character (e.g. trainer format PPL mods)
`nil` if neither of them, meaning a regular selected character without subcharacters.

In beta it always contains the character actually selected by the player, meaning that if a player selected random character, then the client will send the character that was the result of the randomization. `character` and `character_is_random` in the message sent to the server will still be different from each other in case the player selected a bundle mod, having the bundle id in `character_is_random` and whatever the subcharacter randomized to in `character`.
Meaning we could actually hotfix his for beta instead by sending `character_is_random` as nil in case it is the same as the `character`.

**Comment by JamesVanBoxtel** [comment]
What is the motivation for not just sending random_character_special_value in beta just like we did in stable?

Is this so if both players have the randomly selected character, it will be on the same on both computers?

If so, how would stable handle the case if it didn't have the passed character? I guess it randomizes anyways?

**Comment by Endaris** [comment]
> What is the motivation for not just sending random_character_special_value in beta just like we did in stable?

I don't think I had any specific motivation for this, it just kind of happened. Also not what makes the game crash. The desired behaviour for this is debatable, we can open an issue and survey for this I guess.

And yes, if you don't have the character, the game recognises that and force rolls among your characters. When trying to reproduce, I was actually able to watch the game that crashed for defauughj initially because I had the used mods (Bumpty and Cordelia) disabled, meaning my game didn't run into that situation where it tried to roll for a sub character that didn't exist.

**Comment by JamesVanBoxtel** [comment]
Thanks for the great explanation, took a couple reads but I think I understand.

If I understand right, stable might crash against stable if one player picks a bundle and the other player doesn't have that bundle?

Maybe we should just always set to nil if the selection is a bundle, and then from now on the actual character picked will be sent and the same on both clients, or random if they don't have it?

**Comment by Endaris** [comment]
No, stable spectator crashes if a player on beta picks a non-bundle character that the spetactor has.

The fix on beta would be to change line 548 in `select_screen` to
```Lua
menuState.character_is_random = (self.players[self.my_player_number].selectedCharacter == self.players[self.my_player_number].character) and nil or self.players[self.my_player_number].selectedCharacter
```
Beta can already handle if that one is nil because I had to keep the compatibility to stable in mind there.

**Comment by JamesVanBoxtel** [comment]
Okay yeah I think it would probably be better to just make that change ok beta.

**Comment by JamesVanBoxtel** [comment]
> No, stable spectator crashes if a player on beta picks a non-bundle character that the spetactor has.
> 
> The fix on beta would be to change line 548 in `select_screen` to
> 
> ```lua
> menuState.character_is_random = (self.players[self.my_player_number].selectedCharacter == self.players[self.my_player_number].character) and nil or self.players[self.my_player_number].selectedCharacter
> ```
> 
> Beta can already handle if that one is nil because I had to keep the compatibility to stable in mind there. That way it matches the behaviour of stable: `nil`, if non-bundle and non-random.

I tried this last night and others were still crashing

**Comment by Endaris** [comment]
Closing as a beta fix is preferred, see #645 for further discussion

**Pull request closed without merging**
