### PR TITLE
Title Screen and scrolling background support

### PR DESCRIPTION
**Pull request by JamesVanBoxtel**
Made a new TilingImage class that supports tiling images that optionally scroll
Made all the backgrounds use tiling image
Added speeds to the theme to allow scrolling of the backgrounds
Added a optional title background to the theme. When set, it will be the first screen 
The menu will also be shifted up as its assumed there is no logo on the main menu
If not set, nothing should change.
Loading strings are implemented better
Removed references to “legacy canvas size” as it doesn’t matter anymore
Reworked the math
Fixed gprint and gprintf to set the color back to white after changing it
Moved main_menu_screen_pos to the theme
Make sure the lobby position isn’t too high so the welcome text is still visible
Resized the base backgrounds as they weren’t the right resolution
Added the copper league image
Fixed the size of the bronze league image

### CODE REVIEW

**Review by Shosoul — CHANGES_REQUESTED** [review]
I'm not sure we should move the position of the menu. There are a lot of themes that have something in that spot where the menu is, so I think it should be kept where it was for now.

I tried opening up the game with one of the old images we used, and this happened:
screenshot_v046-2022-05-07-14-35-34

Nice concept though!

**Comment by JamesVanBoxtel** [comment]
We only move the menu if you have a title screen. I specifically updated the main theme to fix the image scaling and add a title screen, but the old themes won't have that and so the menu won't move.

**Comment by Shosoul** [comment]
I am slightly confused by what you mean by that. This is the theme I use on the regular, so I got this on opening the game.

**Comment by JamesVanBoxtel** [comment]
Based on discussion with Shosoul there is three things we want to look into doing:

1. Don't tile backgrounds by default, instead add a theme json parameter for that
2. Center the menu vertically and horizontally
3. Log warnings and errors to a file

**Review by Shosoul — APPROVED** [review]

**Pull request merged**
