### PR TITLE
Preserve color for puzzles upon failure

### PR DESCRIPTION
**Pull request by Endaris**
Solves #520, slightly jank but I don't see an elegant way to achieve this.

### CODE REVIEW

**Comment by JamesVanBoxtel** [comment]
Figured out a cleaner way we can do this.

Inside the setup function there is a "musicSetup" function. That is actually only run the first time we select the puzzle set each time. So we can just do something like this inside there.


`if not initialSetup then
      if config.puzzle_randomColors then
        puzzleSet = deepcpy(puzzleSet)
    
        for _, puzzle in pairs(puzzleSet.puzzles) do
          puzzle.stack = Puzzle.randomizeColorString(puzzle.stack)
        end
      end`


and remove the randomizing of colors later inside the puzzle state

**Comment by JamesVanBoxtel** [comment]
Figured out a cleaner way we can do this.

Inside the setup function there is a "musicSetup" function. That is actually only run the first time we select the puzzle set each time. So we can just do something like this inside there.


`if not initialSetup then
      if config.puzzle_randomColors then
        puzzleSet = deepcpy(puzzleSet)
    
        for _, puzzle in pairs(puzzleSet.puzzles) do
          puzzle.stack = Puzzle.randomizeColorString(puzzle.stack)
        end
      end`


and remove the randomizing of colors later inside the puzzle state

**Comment by Endaris** [comment]
Is there any specific reason to make this inside next_func instead of simply putting it at the start of `makeSelectPuzzleSetFunction`?

**Comment by JamesVanBoxtel** [comment]
> Is there any specific reason to make this inside next_func instead of simply putting it at the start of `makeSelectPuzzleSetFunction`?

Yeah its confusing but makeSelectPuzzleSetFunction is called on creation of the menu, not when its selected, everything inside nextFunc is run on select or game over, and musicSetup is only true the first select, so we could rename that and use it for setup purposes

**Comment by Endaris** [comment]
Lol, that's super weird, moved it into a local function that is now getting called inside next_func and added a comment for documenting that unintuitive behaviour.

**Comment by JamesVanBoxtel** [comment]
.randomizeColors is now unused, can we remove all references to it? Other than that this looks good

**Review by JamesVanBoxtel — APPROVED** [review]

**Review by Shosoul — APPROVED** [review]

**Pull request merged**
