### PR TITLE
Create daily leaderboard backups

### PR DESCRIPTION
**Pull request by Endaris**
Solves #607 or starts creating the "database" for creating said statistics.

Maybe slightly misleading cause rn it creates the backup for the day at the START of each day rather than the end but I didn't see a convenient way to math around with the date functions lua offers.

### CODE REVIEW

**Comment by Shosoul** [comment]
I actually already have a script that does this already on the server

**Comment by Endaris** [comment]
> I actually already have a script that does this already on the server

#opensource
Should be part of the repo then.

**Comment by Endaris** [comment]
> I don't think this is the right way to do this. I'm backing up the leaderboard manually every-once in a while along with shosoul, and we are going to track this better when we have a database.

Any data we don't save now will be lost in the future and it's not like a database PR has been submitted and reviewed already. Backing up the leaderboard "once in a while" is less than daily.
I'm happy to close this one if Shosoul's thing does automatically create backups already but I still think that should be added to the repo in turn then.

**Comment by Shosoul** [comment]
My thing automatically backs up the leaderboard daily without my interaction whatsoever

**Comment by Endaris** [comment]
@Shosoul closing this but is there any reason why your solution should not be part of the repo?

**Comment by Shosoul** [comment]
I can put in the script later, yea. It's just a bash script that copies the file to a folder in my personal home directory every day.

**Pull request closed without merging**
