### PR TITLE
Proxy function for "paging"

### PR DESCRIPTION
**Pull request by Endaris**
Had this idea when working on https://github.com/panel-attack/panel-attack/pull/493#issuecomment-1109143307
Shouldn't have any impact, just make things more transparent for debugging.
I only changed it to the new method for the game over transition so far for testing, if you think this is good to have, I'll go through the rest of the repo and change it for the other things as well.

### CODE REVIEW

**Comment by Shosoul** [comment]
Not sure if I totally agree with paging, is there more reasons to do it? It seems like it might make it more complicated and it makes the methods become global instead of local.

**Comment by Endaris** [comment]
Except for the two methods I changed, all other methods were global already.
I feel like if you wanted good scoping you'd need to rework a lot from the grounds up so this feels okay to me.
In which way do you feel this becomes more complicated?
If you want to add a new menu, all you need to do is add it to the list in consts and add a forwarding call in callPageFunc.

I do not actually intend to implement paging and effectively it isn't paging, cause that would be stuff like implementing select_screen as a generic page - which would maybe be good but is not the purpose of this.
As mentioned, the purpose is to circumvent Lua's shortcoming of lacking a nameof(func) function in the specific context of that loop. If you think a different name for the function / array would be better, then I'll be happy to rename, pages are just what I conceptually had in my head.

**Comment by Shosoul** [comment]
It just doesn't seem necessary to me, honestly. It adds a large block of code that has to be hardcoded in. It adds several if statements the game may have to run through and adds more variables to the game than before.

**Comment by Endaris** [comment]
The if statements are only being run when you're changing screens so performance impact should be effectively non-existent.

Personally I consider that extra block of code as useful information instead of redundant information because it organises and compiles the existing screens, centralising the information in one place, making the code more readable and future problems with screen changes easier to troubleshoot.
 When I first got a crash inside that loop I didn't even know it was the loop responsible for switching between screens because it just wasn't apparent, only slightly hinted by the leftovertime comment and any function could get called by it.

**Comment by Shosoul** [comment]
I still believe it's unnecessary to do, but it's something that we just happen to disagree with, since it also creates more globals and hardcoded variables. If james wants to put in his input I'll go with whatever he thinks as a tiebreaker. I believe there are cases where paging is necessary, but I just don't think we need to do it here.

**Comment by JamesVanBoxtel** [comment]
I think we should treat each "page" as its own first class object rather than having a mapping of numbers like this.

In Sankyrs scene branch each of these is a "scene" and it is broken into its own file which makes everything really clean. I think it will be good if we just prioritize the work of getting that branch integrated so we get maximum benefit and architecture.

**Pull request closed without merging**
