### PR TITLE
232 Code Cleanup

### PR DESCRIPTION
**Pull request by Sankyr**
Journey to adding 3D mode to PanelAttack.
Broken up into a 3 phase plan:
 - phase 1:
   - main goal is to move mainloop from a single coroutine to a structed scene system and decoupling/encapsulating as much stuff as possible on the way (removing globals, moving vars/function, etc).
this is for the goal of making changes easier to track and the code easier to follow to prevent future mistakes.
 - phase 2:
   - is to then first understand the engine, then see if there is room for cleaner separations between components. with the goal of making 3d mode as easy to hot swap as possible.
 - phase 3:
   - is the actual 3d mode implementation

Phase 1 breakdown (the contents of this PR):
 - Added scene system
   - All screens are broken up into scenes which will contain everything needed to update & render it.
   - Transitions are standardized and customizable
   - This will replace the existing mainloop with a scene system that will update/draw the current scene without the need to wrap them in a coroutine
 - Added a UI suite (Buttons, ButtonGroups, TextBoxes, Sliders, Labels)
   - this will standardize how the interface works and make it easier to unify touch and mouse controls across the board
 - Created a new input system
   - Existing inputs were tied to the variableStep(), new input system exist outside of variableStep()

TODO:
 - Create custom run that runs at 60fps without needing to waste time sleeping
   - This will remove the need for a custom variable step for 60 fps updates without needing to enable vsync (win/win)

### CODE REVIEW

**Comment by Sankyr** [comment]
There's a reason it's the only thing under TODO, I haven't started it yet. Too many things rely on the current variable step for me to jump into that immediately, only after I port everything to scenes will I add the custom run.

Details:
I strongly believe there is no reason to have variable update rates within PanelAttack, I have heard some reasons why it is how it is atm (something to do with rollback updates?) but I think those can also be done within a 60Hz update loop.
Vsync is not the answer because of LOVE's implementation (its blocking call between updates, wasting CPU cycles).
However simply moving the 60Hz lock to update() isn't right either because it would drop inputs outside of the 60/1000 updates that runs per second.
We would essentially need to move the variable step locking logic to run itself to achieve the intended behavior.

**Comment by Shosoul** [comment]
I'm merely saying that it's why a lot of people played with it off, I'm not saying that you haven't found a solution without it! I'm really looking forward to taking a look-see at this.

**Comment by Sankyr** [comment]
Also I can confirm myself that I feel a difference with VSync on, but I suspect that is due to how it interacts with the system and not VSync alone. Since I haven't messed with the game yet I can't confirm there, but if you noticed lag in the menus with Vsync try my menu and see if does the same thing.

**Comment by Endaris** [comment]
Okay, I feel like your doubts whether this is going to be the right thing to do are legit but since Sankyr is set on trying it, I think it is best to leave that discussion for later when we will actually be able to gauge how well it performs. If the results are obviously bad then Sankyr won't have any reason to press it and if they're comparable to what we have now, most of your doubts will be cleared up.

I think what we should focus on for now are the existing changes to the menu and under which conditions we can / want to pull them into the client.
Take the slider object for example, I feel like after a restyling to the current visuals and improvement of touch support that would already be a small improvement to the game.
The button group for difficulty selection also seems like a great change compared to the clunky type of left+right inputs for difficulty controls we have right now or that Jam used in #497 once touch support is added.
While I agree with Shosouls PoV that an overhaul of the main UI is not our most pressing problem, if we have someone who does it I think there's little reason to not embrace it (while completely ignoring the questionable endgoal of 3D huehue). While most of the current UI code (except select_screen) is not totally messy, we recently identified in the Title Screen debate that we're not using our UI space well and I feel like with Sankyr's UI engine it is certainly going to be a lot easier to rework / redesign things in the future, simply because we don't have any servicable UI classes aside from Click_Menu right now.

Personally I would propose that we work on pulling #497, push that to live and then have Sankyr mimic those changes in his framework alongside with improving on the touch support for those elements and create a pull request that then replaces the menu for endless and time attack (and training mode maybe too?). That way we can ensure that in future pulls these new UI elements already proved themselves, gain the benefit of the new UI elements and open a contribution path for Sankyr to get his changes live instead of always having to work in parallel as well as ensuring that the foundation of his work is getting stabilized by test / review so that later we don't have to put up with a giant pull request of things that kinda work and kinda not.

**Comment by Sankyr** [comment]
I think the minimum change required before what already exist can land is getting the inputs fully functional again, I just started work on that should it wouldn't take me too long to finish (though I'm going to be away for the rest of the week). After that it should be a matter of how much jank you guys would be willing to accept (by jank I mean leaving the codebase between systems & various inconsistencies/inefficienties in implementation)

**Comment by Sankyr** [comment]
Ah, I misunderstood your comment, ya I'll gladly mimic any changes made to alpha (that's what I have been doing so far, I've been more worried there might have been a change that I missed in a merge, such as the love version text and error reporting, I had to re-add/fix those after the merge cause I messed it up)

**Comment by JamesVanBoxtel** [comment]
Closing for now as I think Sankyr is working on a new branch

**Comment by JamesVanBoxtel** [comment]
Closing for now as I think Sankyr is working on a new branch

**Pull request closed without merging**
