### PR TITLE
Create common entry point for CPUs

### PR DESCRIPTION
**Pull request by Endaris**
I'm not sure if I might have inadvertently broken something in your CPU by changing the way the stack is passed through but this would be my general idea.
set+getConfig for menuing and aside from them it essentially just passes through the config and stack and requests the input.

### CODE REVIEW

**Review by Shosoul — APPROVED** [review]

**Review by JamesVanBoxtel — COMMENTED** [review]
Overall this looks good. Can you instead name my computer "TreeSearchComputer" since it really shouldn't have my name and should give an idea what it does.

Also did you test my computer still works?

**Comment by Endaris** [comment]
Your CPU still works and does moves, however I have no way to confirm whether it works exactly how it was previously but I'm optimistic.
If possible can you rename your Cpu yourself? I already have some more commits on that branch locally for my CPU and I'm not sure how I can work the git magic to only include the name change of the class into the PR when pushing.

**Comment by JamesVanBoxtel** [comment]
Thats fine, you can go ahead and land this and I'll figure it out later.

**Comment by JamesVanBoxtel** [comment]
Moving this to a draft until its closer to landing

**Pull request closed without merging**
